frontend: add device password recommendation
BitBoxSwiss/bitbox-wallet-app pull request #2643
Opened 2024-03-21 11:06 UTC by sutterseba

Adding a small note below the password demo video when setting the device password, recommending to choose five to seven characters, helps prevent users from setting extremely long device passwords.

The recommendation is based on the [knowledge base entry](https://shiftcrypto.support/help/en-us/3-basics/84-wie-lange-sollte-mein-geratepasswort-sein), explaining how the BitBox02 protects against brute-force attacks on the device password (reset after 10 failed attempts and permanent device lock after roughly 730.000 total attempts).

To avoid confusion with BIP-39 passphrases, "password" has been rephrased to "device password".

**Preview:**
<img width="1231" alt="Screenshot 2024-03-21 at 11 56 57" src="https://github.com/digitalbitbox/bitbox-wallet-app/assets/79049748/ca955254-7e43-4a79-9dc5-f6ad46fa8d51">

2024-03-22 08:33 UTC, thisconnect requested changes

2024-03-22 08:33 UTC, thisconnect commented on frontends/web/src/routes/device/bitbox02/setup/password.tsx
> +    return 'https://shiftcrypto.support/help/en-us/3-basics/84-wie-lange-sollte-mein-geratepasswort-sein';
nit: if you change from german to english the uri still contains the german verision. (silly knowledge base tool).

please use 
https://shiftcrypto.support/help/en-us/3-basics/84-how-long-should-my-device-password-be

2024-03-22 08:34 UTC, thisconnect commented
could you paste a screenshot of SetPasswordWithBackup ?

2024-03-22 08:47 UTC, sutterseba commented
SetPasswordWithBackup:

<img width="1287" alt="Screenshot 2024-03-22 at 09 42 29" src="https://github.com/digitalbitbox/bitbox-wallet-app/assets/79049748/a965c38c-bf13-4d24-8469-72ab2b4a3a38">

2024-07-02 09:58 UTC, thisconnect commented
I think we should close this as discussed in private. Reaons:
- we don't to add links/buttons to leave the workflow while setting up their wallet
- coming up with real random is really difficult for humans
- recommending something new may lead to uncertainty for existings users.. "is my BB now insecure because I used a pwd length of only 4"
- what is the equivalent of 5 random upp/lower/numbers in lowercase only etc.
- also imo we don't explain fully, i.e. after reading the KB the user currently cannot make an educated choice, i.e what does it mean to not set a password at all, what does a weak password protect against

for these reasons I think we should close this for now and rethink if/how/where to inform

2024-07-06 13:31 UTC, closed without merging