frontend: bump flag-icons dep. to latest 7.2.3
BitBoxSwiss/bitbox-wallet-app pull request #2746
Opened 2024-06-06 16:16 UTC by NicolaLS

no breaking changes, simple update.

flag-icons [CHANGELOG.md](https://github.com/lipis/flag-icons/blob/main/CHANGELOG.md)

2024-06-06 16:25 UTC, NicolaLS commented
(tested on `webdev` chrome)
![flags-screenshot](https://github.com/BitBoxSwiss/bitbox-wallet-app/assets/90551797/7ca44f33-da64-403e-8876-ff12544dc61b)

2024-06-07 06:19 UTC, thisconnect requested changes

2024-06-07 06:19 UTC, thisconnect commented on frontends/web/package.json
> +    "flag-icons": "^7.2.3",
please use `--save-exact` see https://github.com/BitBoxSwiss/bitbox-wallet-app?tab=readme-ov-file#npm-dependencies

2024-06-07 14:49 UTC, NicolaLS commented on frontends/web/package.json
> +    "flag-icons": "^7.2.3",
done/rebased @thisconnect

2024-06-08 06:41 UTC, thisconnect approved these changes
thanks tested LGTM

(FYI: I usually check Nepal flag as it has a special none-rectangle form)

2024-06-08 06:41 UTC, merged