backend: sort unconfirmed transactions by created time
BitBoxSwiss/bitbox-wallet-app pull request #2766
Opened 2024-06-12 12:23 UTC by strmci

This commit updates the transaction history sorting to handle multiple unconfirmed transactions. These transactions are now sorted by their created time.

2024-06-12 13:02 UTC, benma commented on backend/accounts/transaction.go
> +		if (s[i].Height == s[j].Height) || (s[i].Height <= 0 && s[j].Height <= 0) {
How does this change the behavior? Unconfirmed transactions have height=-1 I thought, so the `s[i].Height == s[j].Height` check that was there before  should have caught that, or not?

2024-06-12 13:04 UTC, benma requested changes
Please adjust the unit test to cover sorting by CreatedTimeStamp with the various options.

2024-06-12 15:33 UTC, strmci commented
> Please adjust the unit test to cover sorting by CreatedTimeStamp with the various options.

@benma updated, PTAL

2024-06-20 13:27 UTC, Beerosagos approved these changes
tACK!

2024-06-25 07:33 UTC, merged