frontend: use Message component for Status
BitBoxSwiss/bitbox-wallet-app pull request #2816
Opened 2024-07-17 11:15 UTC by shonsirsha

to improve consistency & aesthetics, we'd like to use our revamped Message component for our Status component.

Please note that our Banner component uses Status. Therefore, with this change, Banner will also use Message component.

<img width="1483" alt="cmp" src="https://github.com/user-attachments/assets/162aa2b7-e454-4aa4-942e-59b71361d59b">
<img width="1483" alt="cma" src="https://github.com/user-attachments/assets/1631904f-e5a7-434d-8224-1bc2eef492e3">
<img width="465" alt="px7" src="https://github.com/user-attachments/assets/549e9cb5-b506-474d-9889-82d7bd5f4c63">
<img width="1483" alt="huj" src="https://github.com/user-attachments/assets/f669c550-9a73-4706-a1de-6c6fddcb3765">

2024-07-23 09:32 UTC, shonsirsha commented
Converting to draft for now as we'd like to also move the position of the banner to be in the content area instead of sticking at top like the screenshots (how it's currently in Master). 

Will add this change as 2nd commit as it's not depending on the first one.

2024-07-23 16:35 UTC, shonsirsha commented
2nd commit:
Adding padding so components that are using Status and were
outside of the content view, to look like they are in the view.

It's done to improve aesthetics.

Preview (SD Card warning):
<img width="1483" alt="kas,ax" src="https://github.com/user-attachments/assets/f63ecd14-050d-43dc-bae4-b94b52124cc7">

Preview (App banner update & mobile data warning):
<img width="1483" alt="vdasd" src="https://github.com/user-attachments/assets/47793dc9-6b0c-40ce-9881-cc90f047d5b5">

2024-07-24 07:45 UTC, shonsirsha commented
Adding padding so components that are using Status and were
outside of the content view, to look like they are in the view.

This is done to improve aesthetics.

Various previews:

<img width="1483" alt="_" src="https://github.com/user-attachments/assets/f9a3c4df-d2ab-4f99-ad56-b570d7f44900">
<img width="1483" alt="_as" src="https://github.com/user-attachments/assets/1eefef86-48ee-4dc5-8300-3e25cbb3ddce">
<img width="612" alt="--jake" src="https://github.com/user-attachments/assets/bf6100f7-ddba-449b-8734-e6f2d1046fd3">
<img width="1483" alt="-jkaem" src="https://github.com/user-attachments/assets/31123ffc-5cbe-4cd1-a97c-1abca6f6d20c">
<img width="1483" alt="__" src="https://github.com/user-attachments/assets/8684fb59-cd9f-4f4f-baa6-c31b37e0a595">

2024-07-29 07:57 UTC, shonsirsha commented
Thanks for the review.
Changes made:
- Created ContentWrapper and removed the padded prop
- Addressed nits (decreased margin on close button of Message and Status' content)
- Removed icon from Status in `passphrase.tsx` by adding a new `noIcon` prop for Message and Status.

and Rebased.

PTAL cc @thisconnect 🙏

2024-07-29 14:06 UTC, thisconnect reviewed
nice, added some nits

the rest looks good, partly tested

2024-07-29 14:06 UTC, thisconnect commented on frontends/web/src/app.module.css
> +    margin-top: var(--space-half);
I'm testing 8cda810 but can't see margin-top with space-half for the sdcard check, also there is div class="undefined" but probably not related.

<img width="1484" alt="Screenshot 2024-07-29 at 15 59 02" src="https://github.com/user-attachments/assets/28daa296-e70a-4df7-be40-400ecca83959">

2024-07-29 14:06 UTC, thisconnect commented on frontends/web/src/components/contentwrapper/contentwrapper.tsx
> +import { ReactNode } from 'react';
please add apache license header

2024-07-31 06:53 UTC, shonsirsha commented on frontends/web/src/app.tsx
> +            <div className="flex flex-column">
> Also is this extra div element needed?

Yes it's needed so that the Banners in the `app.tsx` scrolls with the content.
Agree w/ the rest.

2024-07-31 06:56 UTC, shonsirsha commented
After testing it a couple of times, I found that this breaks this view.

<img width="900" alt="Screenshot 2024-07-31 at 08 55 29" src="https://github.com/user-attachments/assets/cb940c9c-2d15-4fe0-a506-76e33f428b51">

Main cause is because the attempt to make the banners scrollable with the content. I'll try to find another way.

2024-08-05 14:04 UTC, shonsirsha commented
Used (moved) "banner" components that lived in `app.tsx` to several pages (account summary, account overview, and all settings page) & rebased.

PTAL @thisconnect 🙏

2024-08-07 10:06 UTC, thisconnect requested changes
tested looks nice 👍

2024-08-07 10:06 UTC, thisconnect commented on frontends/web/src/routes/settings/manage-accounts.tsx
> +            </ContentWrapper>
please also add it to frontends/web/src/routes/settings/mobile-settings.tsx

2024-08-08 08:04 UTC, shonsirsha commented on frontends/web/src/components/contentwrapper/contentwrapper.tsx
> +});
You're right this was due to my experimentation w/ dynamic height change. Not needed anymore.

2024-08-08 08:07 UTC, shonsirsha commented
Changes made, PTAL 🙏 @thisconnect

2024-08-08 11:50 UTC, thisconnect approved these changes
partly tested, LGTM 👍  with small nit.

2024-08-08 11:50 UTC, thisconnect commented on frontends/web/src/api/banners.ts
> +import { TMessageTypes } from '@/utils/types';
nit: `import type`

2024-08-08 11:50 UTC, thisconnect commented on frontends/web/src/components/contentwrapper/contentwrapper.tsx
> +// Copyright 2024 Shift Crypto AG
nit: in other places the license header uses `/**
 *`

2024-08-08 11:50 UTC, thisconnect commented on frontends/web/src/components/globalbanners/globalbanners.tsx
> +
nit: unused newline 🤓

2024-08-12 08:27 UTC, merged