frontend: create coin control sub-component
BitBoxSwiss/bitbox-wallet-app pull request #2872
Opened 2024-08-27 17:58 UTC by NicolaLS

After: #2870 **and** #2866 

Create a sub-component for the coin control (toggle and utxo selection dialog) to make the `send.tsx` component smaller and easier to understand.

2024-09-02 15:57 UTC, NicolaLS commented
(rebased)

2024-09-02 16:01 UTC, NicolaLS commented
rebased / also amended the commit message to explain the change from https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2870

2024-09-09 08:40 UTC, thisconnect requested changes
nice thank you 👍 

tested LGTM with some nits.

2024-09-09 08:40 UTC, thisconnect commented on frontends/web/src/routes/account/send/send.tsx
> -        this.selectedUTXOs = {};
note for myself: I was quickly confused why this is gone, but it looks like toggleCoinControl was only used to open the dialog and activeCoinControl never true.

2024-09-09 08:40 UTC, thisconnect commented on frontends/web/src/routes/account/send/coin-control.tsx
> +import { useTranslation } from 'react-i18next';
Please add license header, and move react import to first import.

2024-09-09 08:40 UTC, thisconnect commented on frontends/web/src/routes/account/send/send.tsx
> +import { CoinControl } from './coin-control';
nit: move CSS import last

2024-09-09 08:40 UTC, thisconnect commented on frontends/web/src/routes/account/send/send.tsx
> +                        disabled={activeScanQR}
ack 👍

2024-09-09 13:52 UTC, NicolaLS commented
@thisconnect thanks! (first push is rebase, second addressed the change requests). PTAL.

2024-09-09 14:11 UTC, thisconnect approved these changes
LGTM

2024-09-09 14:11 UTC, merged