Lazy load lang defaults
BitBoxSwiss/bitbox-wallet-app pull request #3053
Opened 2024-11-15 07:28 UTC by thisconnect

2024-11-25 11:11 UTC, thisconnect commented on frontends/web/src/i18n/i18n.ts
> -loadLanguage(defaultLang);
This is the relevant change: in this commit I changed @cstenglein initial default loading with a initialized callback see below. cc @shonsirsha

2024-11-26 16:00 UTC, thisconnect commented
rebased

2024-12-06 08:18 UTC, thisconnect commented
rebased

2024-12-06 08:33 UTC, thisconnect commented
I noticed that for me on macOS (at least in `make servewallet`) the native locale endpoint returns an empty string.

```
 % locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

% defaults read -g AppleLanguages
(
    "en-US",
    "de-CH"
)

% defaults read -g AppleLocale
en_US@rg=chzzzz

```

added a commit to "fix" the backend by trying `defaults read -g AppleLocale` or just falling back to en_US, @Beerosagos could you take a look at my last commit?

2024-12-06 09:02 UTC, benma requested changes
Checked only the servewallet locale commit.

Wouldn't it be also good to have the frontend be able to handle invalid or missing locale info? Not sure what the issue was exactly, but I can imagine that the locale might not be detected properly on some platforms in some cases.

2024-12-06 09:02 UTC, benma commented on cmd/servewallet/main.go
> +	if v == "" {
` && runtime.GOOS == "darwin"`

2024-12-06 09:30 UTC, thisconnect commented on cmd/servewallet/main.go
> +	if v == "" {
thanks ❤️  updated with `&& runtime.GOOS == "darwin"`

2024-12-06 11:01 UTC, thisconnect commented
> Wouldn't it be also good to have the frontend be able to handle invalid or missing locale info?

I does already to a certain degree, but I need to test a bit more, what happens if there is really weird invalid data I believe worst case it just fallsback to EN.

https://github.com/BitBoxSwiss/bitbox-wallet-app/blob/9a74ab410863f1a01ae8effc82a8040eab340b66/frontends/web/src/i18n/utils.ts#L17-L25

> Not sure what the issue was exactly

If no userLang has been set the app tries to fallback to the navite lang from the OS, if that doesn't work it fallsback to 'en'.

I found and fixed another issue, that missing keys didn't fallback to en (fixed with last commit).

I'll test a bit more with invalid data later...

2025-01-04 14:32 UTC, thisconnect commented
rebased

2025-01-04 14:45 UTC, thisconnect commented
> I'll test a bit more with invalid data later.

pushed a commit that updated i18n tests with unknown, empty and invalid native locales

2025-01-06 09:30 UTC, benma approved these changes

2025-01-06 09:35 UTC, merged

2025-01-07 04:35 UTC, cstenglein commented
Hi,

sorry for not answering, have been busy these last months. :(
Thank you for finishing the PR on my behalf 🙏!

2025-01-08 09:10 UTC, thisconnect commented
@cstenglein thank you for the initial version 🙏